name: SendSmartMessage_build_main

on:
  push:
    branches:    
      - main
    paths:
      - 'ArenaInteractive/**'
  workflow_dispatch:

jobs:
  linux_build:
    name: build on Ubuntu
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_main_partner.yml@main
    with:
      workdir: ArenaInteractive
      